name = "asip"
main = "./spa-worker.js"
compatibility_date = "2026-08-31"
workers_dev = true

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
html_handling = "auto-trailing-slash"
